CREATE DATABASE PADARIA;
USE PADARIA;
CREATE TABLE PRODUTO(
	CodigoProduto INT PRIMARY KEY AUTO_INCREMENT,
	CodigoBarras VARCHAR (50) NULL,
	Descricao VARCHAR (50) NOT NULL,
	Quantidade INT (11) NOT NULL,
	ValorUnitario DECIMAL (10,4) NOT NULL,
	QuantidadeMinima INT (11) NOT NULL,
	CodigoUnMedida INT NOT NULL,	
	FOREIGN KEY(CodigoUnMedida)
	REFERENCES UNIDADE_MEDIDA(CodigoUnMedida)
	
);

CREATE TABLE UNIDADE_MEDIDA(
	CodigoUnMedida INT PRIMARY KEY AUTO_INCREMENT,
	Descricao VARCHAR (50) NOT NULL
);

CREATE TABLE CATEGORIA(
	Codigo INT PRIMARY KEY AUTO_INCREMENT,
	Descricao VARCHAR (50) NOT NULL
);

CREATE TABLE USUARIO(
	CodigoUsuario INT PRIMARY KEY AUTO_INCREMENT,
	Nome VARCHAR (50) UNIQUE NOT NULL,
	Senha VARCHAR (100) NOT NULL,
	Status BIT NOT NULL,
	CodigoPerfil INT NOT NULL,
	FOREIGN KEY(CodigoPerfil)
	REFERENCES PERFIL(CodigoPerfil)
);

CREATE TABLE PERFIL(
	CodigoPerfil INT PRIMARY KEY AUTO_INCREMENT,
	Descricao VARCHAR(50)
);

CREATE TABLE MOVIMENTO(
	CodigoMovimento INT PRIMARY KEY AUTO_INCREMENT,
	DataHora DATETIME NOT NULL,
	Valor DECIMAL (10,4) NOT NULL,
	Tipo VARCHAR (20) NOT NULL,
	CodigoUsuario INT NOT NULL,
	FOREIGN KEY (CodigoUsuario)
	REFERENCES USUARIO(CodigoUsuario)
);

CREATE TABLE COMANDA (
	CodigoComanda INT PRIMARY KEY AUTO_INCREMENT,
	DataHora DATETIME NOT NULL,
	CodigoUsuario INT NOT NULL,
	FOREIGN KEY (CodigoUsuario)
	REFERENCES USUARIO(CodigoUsuario)
);

CREATE TABLE ITEM (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	Quantidade INT (5) NOT NULL,
	ValorUnitario DECIMAL(10,4) NOT NULL,
	CodigoProduto INT NOT NULL,
	FOREIGN KEY (CodigoProduto)
	REFERENCES PRODUTO (CodigoProduto),
	CodigoComanda INT NOT NULL,
	FOREIGN KEY (CodigoComanda)
	REFERENCES COMANDA (CodigoComanda)
);















